### ISSUE TITLE
TypeError: rotate() got an unexpected keyword argument 'fillcolor'

### ISSUE THREAD

**Issue by Conor52121** [kennethwdk/MLCReID#1]
Hi, when I used the training instructions, two errors occurred. I use the torch 1.14. Would you like to help me fix this problem? Thank you.
'TRAIN': {'BATCH_SIZE': 128,
           'BEGIN_EPOCH': 0,
           'CHECKPOINT': '',
           'END_EPOCH': 60,
           'LR': 0.1,
           'LR_FACTOR': 0.1,
           'LR_STEP': 40,
           'MOMENTUM': 0.9,
           'NESTEROV': True,
           'OPTIMIZER': 'sgd',
           'RESUME': False,
           'SHUFFLE': True,
           'WEIGHT_DECAY': 0.0005},
 'WORKERS': 8}
DataSet market loaded
  subset   | # ids | # images
  ---------------------------
  train    | 'Unknown' |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
Traceback (most recent call last):
  File "tools/train.py", line 186, in <module>
    main()
  File "tools/train.py", line 158, in main
    trainer.train(epoch, train_loader, optimizer)
  File "/home/programs/MLCReID-master/tools/../lib/trainer.py", line 26, in train
    for i, inputs in enumerate(data_loader):
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/programs/MLCReID-master/tools/../lib/utils/data/preprocessor.py", line 48, in __getitem__
    return self._get_single_item(indices)
  File "/home/programs/MLCReID-master/tools/../lib/utils/data/preprocessor.py", line 68, in _get_single_item
    img = self.transform(img)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 1003, in __call__
    return F.rotate(img, angle, self.resample, self.expand, self.center, self.fill)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 729, in rotate
    return img.rotate(angle, resample, expand, center, fillcolor=fill)
TypeError: rotate() got an unexpected keyword argument 'fillcolor'

**Comment by kennethwdk** [comment]
This may be caused by PIL version. You can refer to this blog.
https://discuss.pytorch.org/t/solved-typeerror-rotate-got-an-unexpected-keyword-argument-fillcolor/68115

**Comment by Conor52121** [comment]
> This may be caused by PIL version. You can refer to this blog.
> https://discuss.pytorch.org/t/solved-typeerror-rotate-got-an-unexpected-keyword-argument-fillcolor/68115


It worked. Thank you very much. But another error occured.


Epoch: [0][98/102], Time 0.623 (0.697), Data 0.000 (0.041), Loss 6.413 (6.394)
Epoch: [0][99/102], Time 0.621 (0.697), Data 0.000 (0.040), Loss 6.414 (6.394)
Epoch: [0][100/102], Time 0.622 (0.696), Data 0.000 (0.040), Loss 6.416 (6.394)
Epoch: [0][101/102], Time 0.622 (0.695), Data 0.000 (0.039), Loss 6.412 (6.395)
Epoch: [0][102/102], Time 1.979 (0.708), Data 0.000 (0.039), Loss 6.406 (6.395)
Test with latest model:
Traceback (most recent call last):
  File "tools/train.py", line 186, in <module>
    main()
  File "tools/train.py", line 163, in main
    dataset.gallery, config.TEST.OUTPUT_FEATURES)
  File "/data2/MLCReID-master/tools/../lib/evaluator.py", line 93, in evaluate
    return evaluate_all(distmat, query=query, gallery=gallery)
  File "/data2/MLCReID-master/tools/../lib/evaluator.py", line 75, in evaluate_all
    mAP, all_cmc = map_cmc(distmat, query_ids, gallery_ids, query_cams, gallery_cams)
  File "/data2/MLCReID-master/tools/../lib/evaluation/ranking.py", line 66, in map_cmc
    aps.append(average_precision_score(y_true, y_score))
  File "/data2/MLCReID-master/tools/../lib/evaluation/ranking.py", line 28, in average_precision_score
    average, sample_weight=sample_weight)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/sklearn/metrics/base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/data2/MLCReID-master/tools/../lib/evaluation/ranking.py", line 24, in _binary_average_precision
    y_true, y_score, sample_weight=sample_weight)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 441, in precision_recall_curve
    sample_weight=sample_weight)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 324, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/sklearn/utils/validation.py", line 54, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X)
  File "/home/anaconda3/envs/torchgpu14/lib/python3.6/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by kennethwdk** [comment]
Sorry I did not encounter this problem (the code has been tested on many different computers), maybe you should debug to see where the NaN appear.
